### PR TITLE
new attempt

### PR DESCRIPTION
**Pull request by alexlib**
Hi Lukas, @lengelen

can you please fork my branch https://github.com/alexlib/pyptv/tree/lengelen-master and try it? 
i think it's all there, just have some strange case where .crd and .fix files contain `NaN` values that I have never seen before. Maybe it's a detection issue, don't know yet. 
But the calibration should apparently work 👍

### CODE REVIEW

**Comment by alexlib** [comment]
> Based on the save_point_sets function, it should read
> file_known = self.MultiParams.plane_name[i]+'_cam'+str(c)+'.tif.fix'
> file_detected = self.MultiParams.plane_name[i]+'_cam'+str(c)+'.tif.crd'

I don't think so. in the fine_orientation we just write to `ori.replace('.ori','crd')` right?

**Comment by alexlib** [comment]
> Requires : from optv.tracking_framebuf import TargetArray

fixed

**Comment by alexlib** [comment]
> Gives error: AttributeError: 'CalibrationGUI' object has no attribute 'cal_points'

fixed

**Comment by lengelen** [comment]
> > Based on the save_point_sets function, it should read
> > file_known = self.MultiParams.plane_name[i]+'_cam'+str(c)+'.tif.fix'
> > file_detected = self.MultiParams.plane_name[i]+'_cam'+str(c)+'.tif.crd'
> 
> I don't think so. in the fine_orientation we just write to `ori.replace('.ori','crd')` right?

Nope, I am correct. I just read the ori file to know the camera name/id, e.g. cam**1**. The variable c is thus a single digit (1, 2, 3, ...), depending on which cameras are specified/used in the parameter folder. 
The complete code reads:

                    c = self.calParams.img_ori[i_cam][-9] # Get camera id
                    file_known = self.MultiParams.plane_name[i]+'_cam'+str(c)+'.tif.fix'
                    file_detected = self.MultiParams.plane_name[i]+'_cam'+str(c)+'.tif.crd'
In save_point_sets, we write to txt_detected = ori.replace('ori', 'crd') and txt_matched = ori.replace('ori', 'fix'), in which the ori file is e.g. cal/calib_a_cam2.tif.ori. So replacing the ori by crd or fix will still include the substring _cam2.
I hope this clarifies it. Of course, you could opt to change how these files are saved/read, but I believe it is consistent with the other files.

**Comment by alexlib** [comment]
when I work with different folders, there's no convention agreement to save always with `_cam`, e.g. I have now `east3.tif` and then all the files are just `east3.tif.ori`, `east3.tif.crd` and so on. 

Also, when I look into `multi_planes.par` I see that `_cam` is already there: 

```
5
cal/calib_a_cam
cal/calib_b_cam
cal/calib_c_cam
cal/calib_d_cam
cal/calib_e_cam
```

**Comment by lengelen** [comment]
OK, I see. If you format the multi_planes.par file like that, it is indeed correct.
And indeed, I checked and although I name them always like that, other test cases do not.
Sorry for my misconception

**Comment by lengelen** [comment]
For completeness, the new pull works as it should.

**The only big issue remains the addpar file.**
I checked with one of my test cases I did in January, and it seems to be something that is still not working for Pyptv in general, so not only related to the multi-plane calibration. For this test case, pyptv-python allowed to fine-tune the distortion parameters (not equal to zero), but Pyptv writes them as zero.

I even tried to initialize the calibration with the addpar-file that I got with pyptv-python, but still, after fine orientation, i get all zeros ...

**Comment by alexlib** [comment]
> For completeness, the new pull works as it should.
> 
> **The only big issue remains the addpar file.**
> I checked with one of my test cases I did in January, and it seems to be something that is still not working for Pyptv in general, so not only related to the multi-plane calibration. For this test case, pyptv-python allowed to fine-tune the distortion parameters (not equal to zero), but Pyptv writes them as zero.
> 
> I even tried to initialize the calibration with the addpar-file that I got with pyptv-python, but still, after fine orientation, i get all zeros ...

please check if addpar works for you in `test_cavity` - maybe the problem is more severe than I thought. Now it's not the multiplane issue - that I apparently solved in pyptv (there was a bug in building up the flags list) 

can  you please also check if multiplane in pbi does converge and show addpar? maybe it was removed there intentionally.

**Comment by alexlib** [comment]
well, apparently I do not know what's really wrong with the additional parameters, i.e. `addpar`. The iterations in `orient` in `calibration.c` fail to converge. The only thing I managed to do is to increase the number of iterations and increase the convergence tolerance, but it's a very ugly workaround. So, if you really need this stuff at the moment - do it on your machine and recompile the `liboptv` 

https://github.com/OpenPTV/openptv/blob/8ae5d97396f9c337dc58280203f907e07b9a75ca/liboptv/src/orientation.c#L21

`#define NUM_ITER  200
#define CONVERGENCE 0.001`


I asked also Yosef @yosefm to take a look, but as he's busy, I guess I'll start digging into the issue. I do not remember that was a huge problem in the past, in any case I'll keep looking at it.

**Comment by lengelen** [comment]
Dear Alex,

Even with the #define NUM_ITER 200 #define CONVERGENCE 0.001, the addpar.file only contains zero distortion coefficients when I test it. The same holds when I run it with the test_cavity. Did you got it working for that test case?

Until this issue is fixed, I will undistort the camera images using other software prior to the entire OpenPTV calibration/tracking. For the undistorted images, the distortion coefficients should be theoretically zero, so Pyptv should give sufficiently good results I assume...

For me as an outsider, it's a bit difficult to see what could cause this problem.
But if I can help you with something, just let me know.

**Comment by alexlib** [comment]
It works for me: 
1. see this fix https://github.com/lengelen/pyptv/pull/3/commits/0fd9a23ea279f57d3c47104d0a8d4c1cbc3afcfc
that sets flags correctly and it was the reason that addpar wasn't changed in the first place. 
2. now there are three situations: a) orientation converges (with modified number of iterations and convergence for the difficult cases) and writes addpar files, b) flags are all set to original values and therefore not written, full calibration does everything without the distortion and converges always, c) the number of iterations is not sufficient or convergence is too high and then I get an error that Convergence failed and therefore I guess addpar are just like before.

**Comment by alexlib** [comment]
@lengelen you can see this repository with the actual values I've got now
https://github.com/OpenPTV/test_multiplane

**Comment by alexlib** [comment]
Ok, here's my best take on this: 

Install `liboptv` with the Cython bindings from here: 
https://github.com/alexlib/openptv/tree/dynamic_convergence

it has an option, instead of returning an error for failed convergence with the 80 iterations and 0.00001 convergence threshold to change first the number of iterations up to 500 (changeable) and increase threshold up to 0.1. Thus I could manage to find the "new better guess" for the additional parameters. 

you can see my attempt and the addpar results in 
https://github.com/OpenPTV/test_multiplane/commit/163412659acaebdae04aa10aa80b715198905c94

**Pull request merged**
