### PR TITLE
First step towards multiplane

### PR DESCRIPTION
**Pull request by lengelen**
I added  function in calibration to write fix and crd files necessary for calibration.
The multiplane function is now temporarily called with the function correspondences, 
It requires a yaml-configuration file, and is at the moment still limited to a single camera (can easily be extended). Problem remains addpar file: full_calibration doesn't optimize the distortion parameters ...

### CODE REVIEW

**Comment by alexlib** [comment]
Thanks @lengelen 
I will take a look. I think we shall avoid at the moment YAML files and keep everything in GUI - need to think how to work around it . I think we need to figure out to let system to work as in the old openptv-python: 
1. user creates several parameter sets, one per plane
2. user calibrates the cameras in every single plane, creating ,crd and ,fix files - the settings are in calibration "use Z" checked in and "combine planes" checked out
3. user creates another folder for multiplane and uses all the .crd and all the .fix files together as a single set of 3d points both options in multiplane are checked in 
4. the parameters (list of the folders) was previously stored in multi_planes.par file but not clear if we can add a GUI. in the past it was a manual file creation. Of course it can be also YAML, but then not sure how to let the python bindings of liboptv to use it. need to read from PBI

**Comment by lengelen** [comment]
Dear Alex,

1. Is easily done, I already checked and using multiple parameter folders still works. It is only not possible to specify which parameter folder is read first when the GUI is started up. Usually not important, unless you want to run with only a subset of cameras.
2. Should be easily included using the modified write function. Only a flag necessary to write the fix and crd files or not, depending on the specification of use Z ...
3. I would add the multiplane calibration step as an additional function in the main menu of the GUI, since it is already based on the previous single plane calibrations.
4. Both are possible indeed, although the yaml configuration now works except for the addpar-file-->??

**Comment by alexlib** [comment]
> Dear Alex,
> 
> 1. Is easily done, I already checked and using multiple parameter folders still works. It is only not possible to specify which parameter folder is read first when the GUI is started up. Usually not important, unless you want to run with only a subset of cameras.
> 2. Should be easily included using the modified write function. Only a flag necessary to write the fix and crd files or not, depending on the specification of use Z ...
> 3. I would add the multiplane calibration step as an additional function in the main menu of the GUI, since it is already based on the previous single plane calibrations.
> 4. Both are possible indeed, although the yaml configuration now works except for the addpar-file-->??

3. - no need to add new GUI button - the settings are in the calibration GUI that are copied to the `examine.par` 0/1 for the multiple calibration (yes or no) and 0/1 in the second row for just saving files or combining planes (1) 
the way it works is - 
if you're in one of the plane folders - your settings are 1,0 and then the calibration is saving files when Orient is pressed
if you're in a multi-plane folder (combining planes) - you change settings to 1,1, and then the multi-plane calibraton function reads `multi_planes.par` and runs the orient_v3 

image

**Comment by lengelen** [comment]
OK, I see, you refer to the lines 
    Examine_Flag = Bool(False, label='Calibrate with different Z')
    Combine_Flag = Bool(False, label='Combine preprocessed planes')
in parameter_gui.py I assume?

So now the multiplane calibration that I added in the ptv.py should be called upon when these flags are set?

My main problem remains the addpar-file that is not changed after calibration ...

**Comment by alexlib** [comment]
> OK, I see, you refer to the lines
> Examine_Flag = Bool(False, label='Calibrate with different Z')
> Combine_Flag = Bool(False, label='Combine preprocessed planes')
> in parameter_gui.py I assume?

Yes - I think inside `ptv.py` when we get a call from `Raw orientation` we check whether these parameters are flagged (by looking into parameters or reading the `examine.par` file in the present parameters directory) and then we know if we're in:
a) usual 3D calibration
b) multiplane calibration, single plane
c) multiplane calibration, multi-plane combination (then one has to read `multi_planes.par`)

> 
> So now the multiplane calibration that I added in the ptv.py should be called upon when these flags are set?

yes, see above


> 
> My main problem remains the addpar-file that is not changed after calibration ...

we'll fix it 👍 I just need some time to take a closer look.

Please note that @yosefm solution is not precisely this one - he used YAML files to contain all the necessary information (no need to check for flags or read parameter files) and also he does camera by camera calibration (in which he does plane by plane) while we do it in a loop at every plane (for all cameras in a single plane). Therefore `pbi` reads multi-plane info for a single camera, while we need multi-plane information for all the cameras.

**Pull request closed without merging**
